--- #################### 数据库相关配置 ####################
spring:
  # 数据源配置项
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cassandre-database?allowMultiQueries=true&useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&nullCatalogMeansCurrent=true # MySQL Connector/J 8.X 连接的示例
    username: root
    password: 123456
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

cassandre.trading.bot: # 市场相关配置
  exchange:   # Exchange configuration.
    driverClassName: org.knowm.xchange.okex.OkexExchange
    username: Wi7oU9itkox7qTVOcKuwb2HPmg9c8Gx3
    passphrase: ZZSgvd6bLwTtZC+KlzAteTphrR+GY88X
    key: 8hx7GsSZKiZM5WMbpswSDT+MBEbk8h3NMpCoRt+96XRqgDrOGHUzgzKHzrAS8IAD
    secret: gfovccbqgb5SVqQ5QMebb73TmWGjUa5d05cNeXwHwZjJkYViP+9xyH+YGU/vQmP+
    modes:  # Modes.
      sandbox: true
      dry: false
    # Exchange API calls rates (In ms or standard ISO 8601 duration like 'PT5S').
    rates:
      account: 100
      ticker: 101
      trade: 102
cassandre.trading.jasypt:
  encryptor:
    password: "启动参数传入或者用插件生成"
    property:
      prefix: "ENC@["
      suffix: "]"