--- #################### 数据库相关配置 ####################
spring:
  # 数据源配置项
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cassandre-database?allowMultiQueries=true&useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&nullCatalogMeansCurrent=true # MySQL Connector/J 8.X 连接的示例
    username: root
    password: 123456
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  liquibase:
    enabled: false
    change-log: classpath:/db/changelog/db.changelog-master.yaml

cassandre.trading.bot: # 市场相关配置
  exchange:   # Exchange configuration.
    driverClassName: org.knowm.xchange.okex.OkexExchange
    username:
    passphrase:
    key:
    secret:
    modes:  # Modes.
      sandbox: true
      dry: false
    # Exchange API calls rates (In ms or standard ISO 8601 duration like 'PT5S').
    rates:
      account: 100
      ticker: 101
      trade: 102
cassandre:
  trading:
    jasypt:
      encryptor:
        password: 启动参数传入
        property:
          prefix: "ENC@["
          suffix: "]"